version: '3.8'
services:
  covidsummary:
    build: ./
    image: tfizz/covid-summary:1.0.0
    restart: always
    ports: 
      - 80:3000
    deploy:
      replicas: 3
      update_config: 
        parallelism: 1
        delay: 10s